targets:
  $default:
    builders:
      vaden_class_scanner|aggregating_vaden_builder:
        enabled: true
      drift_dev:
        options:
          sql:
            dialects:
              - postgres

