version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: banking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking_master
      POSTGRES_PASSWORD: banking_master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - banking_network

volumes:
  postgres_data:
    driver: local

networks:
  banking_network:
    driver: bridge
