name: backend
description: backendpara o BAKING app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.2
  vaden_security: ^0.0.8
  vaden: ^0.1.3

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.1.3