name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  vaden_core: ^0.0.3
  decimal: ^3.2.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
